name: Pack Conotoso_University
on:
  push:
    paths:
      - contents/**


jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: out/DevSolution.zip
          solution-folder: contents
          solution-type: Unmanaged
      - uses: actions/upload-artifact@v2
        with:
          name: packed-solution
          path: out/